# Generated by Django 3.2.9 on 2021-11-20 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_parser/csv/')),
                ('name', models.CharField(max_length=1000, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование')),
                ('level_one', models.CharField(max_length=1000, verbose_name='Уровень1')),
                ('level_two', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Уровень2')),
                ('level_three', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Уровень3')),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('sp_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена СП')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('property_fields', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Поля свойств')),
                ('joint_purchases', models.CharField(blank=True, choices=[('0', 'Нет'), ('1', 'Да')], max_length=100, null=True, verbose_name='Совместные покупки')),
                ('measurement_unit', models.CharField(max_length=200, verbose_name='Единица измерения')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='csv_parser/pictures/', verbose_name='Картинка')),
                ('is_display', models.CharField(blank=True, choices=[('0', 'Нет'), ('1', 'Да')], max_length=100, null=True, verbose_name='Выводить на главной')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('file_id', models.PositiveIntegerField(verbose_name='ID загруженного файла')),
            ],
        ),
    ]
