# Generated by Django 3.2.9 on 2021-11-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'Файл .csv', 'verbose_name_plural': 'Файлы .csv'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sp_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена СП'),
        ),
    ]
